"""initial schema

Revision ID: e6d8c3082aca
Revises: 
Create Date: 2026-08-22 04:23:15.355773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d8c3082aca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ats_platform', sa.String(length=32), nullable=False),
    sa.Column('endpoint_url', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('weekly_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.DateTime(), nullable=False),
    sa.Column('brief_markdown', sa.Text(), nullable=False),
    sa.Column('signal_json', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_slug', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('raw_department', sa.String(length=256), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('employment_type', sa.String(length=64), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_slug'], ['companies.slug'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_slug', 'external_id', name='uq_company_external')
    )
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.create_index('ix_company_open', ['company_slug', 'is_open'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_company_slug'), ['company_slug'], unique=False)

    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_slug', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('records_found', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_slug'], ['companies.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_runs_company_slug'), ['company_slug'], unique=False)

    op.create_table('posting_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posting_id', sa.Integer(), nullable=False),
    sa.Column('function_category', sa.String(length=128), nullable=False),
    sa.Column('seniority_level', sa.String(length=64), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('classified_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['job_postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posting_classifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posting_classifications_posting_id'), ['posting_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posting_classifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posting_classifications_posting_id'))

    op.drop_table('posting_classifications')
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_runs_company_slug'))

    op.drop_table('scrape_runs')
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_postings_company_slug'))
        batch_op.drop_index('ix_company_open')

    op.drop_table('job_postings')
    op.drop_table('weekly_briefs')
    op.drop_table('companies')
    # ### end Alembic commands ###
